ARG ATMOSPHERE=flat
ARG CORSIKA=77500

FROM almalinux:9.3 AS build_image
WORKDIR /workdir

RUN yum update -y && yum install -y \
    csh \
    perl \
    gcc-fortran && \
    yum clean all

ADD corsika-${CORSIKA}.tar.gz .
# CORSIKA compile options derived with coconut
COPY ./docker/corsika-config-$ATMOSPHERE.h corsika-${CORSIKA}/include/config.h

# build corsika
WORKDIR /workdir/corsika-${CORSIKA}
RUN ./coconut < /dev/null

SHELL ["/bin/bash", "-c"]
WORKDIR /workdir/

FROM almalinux:9.3-minimal
LABEL maintainer.name="VERITAS Collaboration"
LABEL maintainer.email="gernot.maier@desy.de"
LABEL org.opencontainers.image.source="https://github.com/VERITAS-Observatory/VTS-SimPipe"
LABEL org.opencontainers.image.description="CORSIKA ${CORSIKA} (non-optimized version) as used for the VERITAS simulation pipeline. Atmosphere: ${ATMOSPHERE}"
LABEL org.opencontainers.image.licenses="BSD-3-Clause"
WORKDIR /workdir
ENV DEBIAN_FRONTEND=noninteractive
COPY --from=build_image /workdir/corsika-${CORSIKA}/run /workdir/corsika-run

RUN microdnf update -y && microdnf install -y \
    gcc-fortran && \
    microdnf clean all

COPY ./config/ATMOSPHERE/atmprof*.dat /workdir/corsika-run/
# qgsjet tables (otherwise CORSIKA generates these tables during startup)
ADD https://syncandshare.desy.de/index.php/s/X9a4c5bYzy5p6nF/download /workdir/corsika-run/tables.dat

SHELL ["/bin/bash", "-c"]
WORKDIR /workdir/
