ARG AVX_FLAG=avx2
ARG ATMOSPHERE=flat
ARG CORSIKA=77500

FROM almalinux:9.3 AS build_image
ARG ATMOSPHERE
ARG AVX_FLAG
ARG CORSIKA
WORKDIR /workdir

RUN yum update -y && yum install -y \
    autoconf \
    automake \
    csh \
    perl \
    gcc-fortran \
    gfortran \
    libgfortran \
    patch &&  \
    yum clean all

ADD corsika-${CORSIKA}.tar.gz .
RUN cd ./corsika-${CORSIKA}/bernlohr && tar -xvzf bernlohr-1.66.tar.gz
ADD corsikaOptPatch-${CORSIKA}_2024-02-05.tar.gz ./corsika-${CORSIKA}
RUN if [ "$AVX_FLAG" != "noopt" ] || [ "$ATMOSPHERE" = "curved" ]; then \
        cd ./corsika-${CORSIKA} && ./corsika_opt_patching.sh && autoreconf; \
    fi
# CORSIKA compile options derived with coconut
COPY ./docker/corsika-config-${ATMOSPHERE}-optimized.h corsika-${CORSIKA}/include/config.h

# build corsika
WORKDIR /workdir/corsika-${CORSIKA}
RUN ./coconut < /dev/null
ENV GCC_PATH="/usr/bin/"
RUN make clean && rm -f */*.a lib/*/*.a && \
    if [ "$AVX_FLAG" != "noopt" ] || [ "$ATMOSPHERE" = "curved" ]; then \
        make \
        CC="${GCC_PATH}/gcc -static" \
        CXX="${GCC_PATH}/g++ -static" \
        CPP="${GCC_PATH}/gcc -static -E" \
        F77="${GCC_PATH}/gfortran -L/lib64/" \
        CFLAGS="-DCERENKOPT -DVLIBM -std=c99 -O3 -m${AVX_FLAG} -DVECTOR_SIZE=8 -DVECTOR_LENGTH=8" \
        CXXFLAGS="-DCERENKOPT -DVLIBM -std=c99 -O3 -m${AVX_FLAG} -DVECTOR_SIZE=8 -DVECTOR_LENGTH=8" \
        # Note: different to CTAO - no change in avx options for Fortran
        # FFLAGS="-ffixed-line-length-132 -fno-automatic -frecord-marker=4 -std=legacy -DCERENKOPT -DVLIBM -std=c99 -O3 -m${AVX_FLAG} -DVECTOR_SIZE=8 -DVECTOR_LENGTH=8" \
        FFLAGS="-ffixed-line-length-132 -fno-automatic -frecord-marker=4 -std=legacy -std=c99 -O3 -mavx2" \
        install; \
    else \
        make \
        CC="${GCC_PATH}/gcc -static" \
        CXX="${GCC_PATH}/g++ -static" \
        CPP="${GCC_PATH}/gcc -static -E" \
        F77="${GCC_PATH}/gfortran" \
        CFLAGS="-std=c99 -O3 -mavx2" \
        CXXFLAGS="-std=c99 -O3 -mavx2" \
        FFLAGS="-ffixed-line-length-132 -fno-automatic -frecord-marker=4 -std=legacy -std=c99 -O3 -mavx2" \
        install; \
    fi
RUN if [ "$AVX_FLAG" != "noopt" ] || [ "$ATMOSPHERE" = "curved" ]; then \
        mv run/corsika${CORSIKA}Linux_QGSII_urqmdceropt run/corsika${CORSIKA}Linux_QGSII_urqmd; \
    fi

SHELL ["/bin/bash", "-c"]
WORKDIR /workdir/

FROM almalinux:9.3-minimal
ARG AVX_FLAG
ARG ATMOSPHERE
ARG CORSIKA
LABEL maintainer.name="VERITAS Collaboration"
LABEL maintainer.email="gernot.maier@desy.de"
LABEL org.opencontainers.image.source="https://github.com/VERITAS-Observatory/VTS-SimPipe"
LABEL org.opencontainers.image.description="CORSIKA ${CORSIKA} (optimized version) as used for the VERITAS simulation pipeline. Atmosphere: ${ATMOSPHERE}"
LABEL org.opencontainers.image.licenses="BSD-3-Clause"
WORKDIR /workdir
ENV DEBIAN_FRONTEND=noninteractive
COPY --from=build_image /workdir/corsika-${CORSIKA}/run /workdir/corsika-run

RUN microdnf update -y && microdnf install -y \
    gcc-fortran && \
    microdnf clean all

COPY ./config/ATMOSPHERE/atmprof*.dat /workdir/corsika-run/
# qgsjet tables (otherwise CORSIKA generates these tables during startup)
ADD https://syncandshare.desy.de/index.php/s/X9a4c5bYzy5p6nF/download /workdir/corsika-run/tables.dat

SHELL ["/bin/bash", "-c"]
WORKDIR /workdir/
